version: "3"

services:
  db:
    image: postgres:latest
    container_name: SIGAA_DATABASE
    env_file: .env
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host}
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgres/data
    networks:
      - sigaa

  nego:
    build: .
    container_name: NEGO_API
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - 8081:8081
      - 80:80
    networks:
      - sigaa

networks:
  sigaa:
